# please set unused arguments to none and do NOT delete them.

download_path: '/run/user/1000/gvfs/smb-share:server=raspberrypi,share=sda1/bangumi'
httpproxy: '127.0.0.1:1983'
email_username: 'zsewqa163@163.com'
email_password: 'zjezPgOoHQA7oboi'
email_receiver: '2257543047@qq.com'
transmissionrpc_server: '23.83.247.48'
#transmissionrpc_server: '127.0.0.1'
transmissionrpc_user: 'your_username11@'
transmissionrpc_password: 'your_password11@'
transmissionrpc_download_path: '/root/Dropbox/Others/bangumi'
#transmissionrpc_download_path: '/home/l/Downloads/bangumi'
aria2_rpc: 'http://token:11@192.168.10.219:6800/jsonrpc'
