星期一,Concrete Revolutio:
  rss:
    傲嬌零: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%B6%85%E4%BA%BA%E5%B9%BB%7CConcrete+team_id%3A532+GB+720+MP4&sort_id=2
  team: 傲嬌零
星期一,一拳超人:
  rss:
    KNA: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%B8%80%E6%8B%B3+team_id%3A498+%E7%B9%81+720+MP4&sort_id=2
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%B8%80%E6%8B%B3+team_id%3A303+%E7%AE%80+720&sort_id=2
    幻櫻: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%B8%80%E6%8B%B3+team_id%3A241+GB+720+MP4&sort_id=2
  team: KNA
星期一,彗星·路西法:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%B7%AF%E8%A5%BF%E6%B3%95%7Clucifer+team_id%3A185+GB+720+MP4&sort_id=2
    澄空.華盟: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%B7%AF%E8%A5%BF%E6%B3%95%7Clucifer+team_id%3A58+720+MP4&sort_id=2
  team: 澄空.華盟
星期三,偵探小隊KZ事件簿:
  rss:
    幻之: https://share.dmhy.org/topics/rss/rss.xml?keyword=KZ%E4%BA%8B+team_id%3A430+GB+720+MP4&sort_id=2
  team: 幻之
星期三,緋彈的亞莉亞AA:
  rss:
    KNA: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B7%8B%E5%BD%88+team_id%3A498+%E7%B9%81+720+MP4&sort_id=2
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B7%8B%E5%BD%88+team_id%3A303+%E7%AE%80+720&sort_id=2
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B7%8B%E5%BD%88+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    幻之: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B7%8B%E5%BD%88+team_id%3A430+GB+720+MP4&sort_id=2
    幻櫻: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B7%8B%E5%BD%88+team_id%3A241+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B7%8B%E5%BD%88+team_id%3A185+GB+720&sort_id=2
    澄空.華盟: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B7%8B%E5%BD%88+team_id%3A49+%E7%AE%80+720+MP4&sort_id=2
  team: 極影
星期二,ToLoveRuDarkness2nd:
  rss:
    千夏.茉語: https://share.dmhy.org/topics/rss/rss.xml?keyword=Darkness+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=Darkness+team_id%3A185+GB+720+MP4&sort_id=2
    華盟.澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=Darkness+team_id%3A49+%E7%AE%80+720+MP4&sort_id=2
  team: 極影
星期二,搖曳百合3☆High!:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%AC%86%E7%99%BE%7C%E6%9B%B3%E7%99%BE+team_id%3A303+%E7%AE%80+720&sort_id=2
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%AC%86%E7%99%BE%7C%E6%9B%B3%E7%99%BE+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
  team: 千夏
星期五,全部成為F:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%82%BAF+team_id%3A185+GB+720+MP4&sort_id=2
    異域: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%82%BAF+team_id%3A271+%E7%AE%80+720&sort_id=2
  team: 極影
星期五,單色小姐Ⅲ:
  rss:
    KNA: https://share.dmhy.org/topics/rss/rss.xml?keyword=Monochrome+team_id%3A498+%E7%B9%81+720+MP4&sort_id=2
  team: KNA
星期六,K Return of Kings:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=return+of+kings+team_id%3A185+GB+720&sort_id=2
    異域: https://share.dmhy.org/topics/rss/rss.xml?keyword=return+of+kings+team_id%3A271+%E7%AE%80+720&sort_id=2
  team: 極影
星期六,偶像大師灰姑娘女孩Ⅱ:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%A8%98%E5%A5%B3%E5%AD%A9%7CCinderella+team_id%3A185+GB+720+MP4&sort_id=2
    澄空.華盟: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%A8%98%E5%A5%B3%E5%AD%A9%7CCinderella+team_id%3A49+720+MP4&sort_id=2
  team: 澄空.華盟
星期六,重裝武器:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%A3%9D%E6%AD%A6%7CHeavy+team_id%3A303+%E7%AE%80+720&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%A3%9D%E6%AD%A6%7CHeavy+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
星期四,我被抓到貴族女校當庶民樣本:
  rss:
    澄空.華盟: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%BA%B6%E6%B0%91+team_id%3A58+720+MP4&sort_id=2
    輕之國度: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%BA%B6%E6%B0%91+team_id%3A321+GB+720+MP4&sort_id=2
  team: 輕之國度
星期四,櫻子小姐腳下埋著屍體:
  rss:
    傲嬌零: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%A7%90+%E5%9F%8B+team_id%3A532+GB+720+MP4&sort_id=2
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%A7%90+%E5%9F%8B+team_id%3A303+%E7%AE%80+720&sort_id=2
    惡魔島: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%A7%90+%E5%9F%8B+team_id%3A90+GB+720+MP4&sort_id=2
  team: 惡魔島
星期四,魔鬼戀人MORE,BLOOD:
  rss:
    幻櫻: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%AD%94%E9%AC%BC+MORE+team_id%3A241+GB+720+MP4&sort_id=2
  team: 幻櫻
星期日,傳頌之物 虛偽的假面:
  rss:
    傲嬌零: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%A0%8C+%E9%9D%A2+team_id%3A532+GB+720+MP4&sort_id=2
    幻櫻: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%A0%8C+%E9%9D%A2+team_id%3A241+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%A0%8C+%E9%9D%A2+team_id%3A185+GB+720+MP4&sort_id=2
    異域: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%A0%8C+%E9%9D%A2+team_id%3A271+%E7%AE%80+720&sort_id=2
    雪飄.澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%A0%8C+%E9%9D%A2+team_id%3A58+720+MP4&sort_id=2
  team: 雪飄.澄空
星期日,小森拒不了!:
  rss:
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%A3%AE%E6%8B%92+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    幻之: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%A3%AE%E6%8B%92+team_id%3A430+GB+720+MP4&sort_id=2
    幻櫻: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%A3%AE%E6%8B%92+team_id%3A241+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%A3%AE%E6%8B%92+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
星期日,溫泉幼精小箱根:
  rss:
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%B9%BC%E7%B2%BE+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    幻之: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%B9%BC%E7%B2%BE+team_id%3A430+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%B9%BC%E7%B2%BE+team_id%3A185+GB+720+MP4&sort_id=2
    澄空學園: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%B9%BC%E7%B2%BE+team_id%3A58+720+MP4&sort_id=2
  team: 澄空學園
星期日,終物語:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B5%82%E7%89%A9%E8%AA%9E+team_id%3A185+GB+720+MP4&sort_id=2
    異域: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B5%82%E7%89%A9%E8%AA%9E+team_id%3A271+%E7%AE%80+720&sort_id=2
    華盟: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B5%82%E7%89%A9%E8%AA%9E+team_id%3A49+%E7%AE%80+720+MP4&sort_id=2
  team: 極影
星期日,終結的熾天使Ⅱ:
  rss:
    惡魔島: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%86%BE%E5%A4%A9+team_id%3A90+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%86%BE%E5%A4%A9+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
星期日,請問您今天要來點兔子嗎??:
  rss:
    KNA: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%BB%9E+%E5%85%94+team_id%3A498+%E7%B9%81+720+MP4&sort_id=2
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%BB%9E+%E5%85%94+team_id%3A303+%E7%AE%80+720&sort_id=2
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%BB%9E+%E5%85%94+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%BB%9E+%E5%85%94+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
星期日,進擊！巨人中學校:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%80%B2+%E4%B8%AD%E5%AD%B8+team_id%3A303+%E7%AE%80+720&sort_id=2
    惡魔島: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%80%B2+%E4%B8%AD%E5%AD%B8+team_id%3A90+GB+720+MP4&sort_id=2
  team: 惡魔島
星期二,JK飯!:
  rss:
    RH: https://share.dmhy.org/topics/rss/rss.xml?keyword=JK+%E9%A3%AF%7CMeshi+team_id%3A425
    吐槽: https://share.dmhy.org/topics/rss/rss.xml?keyword=JK+%E9%A3%AF%7CMeshi+team_id%3A540
  team: RH
星期日,機動戰士高達 鐵血的孤兒:
  rss:
    NEO·QSW: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%A9%9F%E5%8B%95+%E9%90%B5%E8%A1%80+team_id%3A537
    動漫花園: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%A9%9F%E5%8B%95+%E9%90%B5%E8%A1%80+team_id%3A117
  team: NEO·QSW
星期六,新妹魔王的契約者BURST:
  rss:
    雪夢: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%96%B0%E5%A6%B9+BURST+team_id%3A567
  team: 雪夢
