星期一,Tawawa on Monday:
  rss:
    幻之: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%80%B1%E4%B8%80%E7%9A%84%7C%E5%91%A8%E4%B8%80%E7%9A%84%7C%E6%9B%B3%E7%9A%84%E6%98%9F%7CTawawa%7C%E3%81%9F%E3%82%8F%E3%82%8F+team_id%3A430+GB+720+MP4&sort_id=2
    幻樱: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%80%B1%E4%B8%80%E7%9A%84%7C%E5%91%A8%E4%B8%80%E7%9A%84%7C%E6%9B%B3%E7%9A%84%E6%98%9F%7CTawawa%7C%E3%81%9F%E3%82%8F%E3%82%8F+team_id%3A241+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%80%B1%E4%B8%80%E7%9A%84%7C%E5%91%A8%E4%B8%80%E7%9A%84%7C%E6%9B%B3%E7%9A%84%E6%98%9F%7CTawawa%7C%E3%81%9F%E3%82%8F%E3%82%8F+team_id%3A185+GB+720+MP4&sort_id=2
    澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%80%B1%E4%B8%80%E7%9A%84%7C%E5%91%A8%E4%B8%80%E7%9A%84%7C%E6%9B%B3%E7%9A%84%E6%98%9F%7CTawawa%7C%E3%81%9F%E3%82%8F%E3%82%8F+team_id%3A58+720+MP4&sort_id=2
  team: 澄空
星期二,斯特拉的魔法:
  rss:
    DHR: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%96%AF%E7%89%B9%E6%8B%89%E7%9A%84+team_id%3A407
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%96%AF%E7%89%B9%E6%8B%89%E7%9A%84+team_id%3A303+%E7%AE%80+720&sort_id=2
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%96%AF%E7%89%B9%E6%8B%89%E7%9A%84+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    喵萌茶會: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%96%AF%E7%89%B9%E6%8B%89%E7%9A%84+team_id%3A468
    桜都: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%96%AF%E7%89%B9%E6%8B%89%E7%9A%84+team_id%3A619
    眾神之王: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%96%AF%E7%89%B9%E6%8B%89%E7%9A%84+team_id%3A645
    紫音: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%96%AF%E7%89%B9%E6%8B%89%E7%9A%84+team_id%3A459
    西农YUI: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%96%AF%E7%89%B9%E6%8B%89%E7%9A%84+team_id%3A525+GB
  team: 西农YUI
星期三,装神少女小纏:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%A3%85%E7%A5%9E%E5%B0%91+team_id%3A303+%E7%AE%80+720&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%A3%85%E7%A5%9E%E5%B0%91+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
星期五,少女編號:
  rss:
    幻之: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%A5%B3%E7%B7%A8+team_id%3A430+GB+720&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%A5%B3%E7%B7%A8+team_id%3A185+GB+720&sort_id=2
  team: 極影
星期五,FLIP FLAPPERS:
  rss:
    SweetSub: https://share.dmhy.org/topics/rss/rss.xml?keyword=FLIP+FLAPPERS+team_id%3A650+MP4+CHS
  team: SweetSub
星期六,Lostorage incited WIXOSS:
  rss:
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=Lostorage+WIXOSS+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=Lostorage+WIXOSS+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
星期四,奏響吧!上低音號2:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%B8%8A%E4%BD%8E%7CEuphonium+team_id%3A185+GB+720+MP4&sort_id=2
    澄空.華盟: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%B8%8A%E4%BD%8E%7CEuphonium+team_id%3A49+%E7%AE%80+720+MP4&sort_id=2
  team: 極影
星期日,ViVid Strike:
  rss:
    澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=ViVid+Strike+team_id%3A58+720+MP4&sort_id=2
  team: 澄空
星期日,終末的伊澤塔:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%BC%8A%E6%BE%A4%E5%A1%94+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
星期日,超自然9人組:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%84%B69%7COccultic+team_id%3A185+GB+720+MP4&sort_id=2
    繁星: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%84%B69%7COccultic+team_id%3A601+GB
  team: 繁星
