星期一,噬神者:
  rss:
    傲嬌零: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%99%AC%E7%A5%9E+team_id%3A532+GB+720+MP4&sort_id=2
    惡魔島: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%99%AC%E7%A5%9E+team_id%3A90+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%99%AC%E7%A5%9E+team_id%3A185+GB+720+MP4&sort_id=2
    異域: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%99%AC%E7%A5%9E+team_id%3A271+%E7%AE%80+720&sort_id=2
  team: 極影
星期二,ToLoveRuDarkness2nd:
  rss:
    千夏.茉語: https://share.dmhy.org/topics/rss/rss.xml?keyword=Darkness+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=Darkness+team_id%3A185+GB+720+MP4&sort_id=2
    華盟.澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=Darkness+team_id%3A49+%E7%AE%80+720+MP4&sort_id=2
  team: 極影
星期二,悠哉日常大王Repeat:
  rss:
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%93%89+%E6%97%A5+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%93%89+%E6%97%A5+team_id%3A185+GB+720+MP4&sort_id=2
    華盟: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%93%89+%E6%97%A5+team_id%3A49+%E7%AE%80+720+MP4&sort_id=2
  team: 極影
星期五,亂步奇譚:
  rss:
    千夏.DHR.茉語: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%BA%82%E6%AD%A5%7CLaplace+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%BA%82%E6%AD%A5%7CLaplace+team_id%3A185+GB+720+MP4&sort_id=2
    澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%BA%82%E6%AD%A5%7CLaplace+team_id%3A58+720+MP4&sort_id=2
  team: 澄空
星期五,城下町的蒲公英:
  rss:
    KNA: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%9A%84%E8%92%B2%7Cdande+team_id%3A498+%E7%B9%81+720+MP4&sort_id=2
    澄空.華盟: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%9A%84%E8%92%B2%7Cdande+team_id%3A58+720+MP4&sort_id=2
  team: KNA
星期五,學園孤島:
  rss:
    KNA.茉語: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%9C%92%E5%AD%A4+team_id%3A498+%E7%B9%81+720+MP4&sort_id=2
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%9C%92%E5%AD%A4+team_id%3A303+%E7%AE%80+720&sort_id=2
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%9C%92%E5%AD%A4+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    幻之.漫貓: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%9C%92%E5%AD%A4+team_id%3A430+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%9C%92%E5%AD%A4+team_id%3A185+GB+720&sort_id=2
  team: 極影
星期五,群居姊妹:
  rss:
    幻之: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%BE%A4%E5%B1%85+team_id%3A430+GB+720+MP4&sort_id=2
  team: 幻之
星期六,Classroom☆Crisis:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=Classroom+Crisis+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
星期六,GATE奇幻自衛隊:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%87%AA%E8%A1%9B%E9%9A%8A+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
星期六,偶像大師灰姑娘女孩Ⅱ:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%A8%98%E5%A5%B3%E5%AD%A9%7CCinderella+team_id%3A185+GB+720+MP4&sort_id=2
    澄空.華盟: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%A8%98%E5%A5%B3%E5%AD%A9%7CCinderella+team_id%3A49+%E7%AE%80+720+MP4&sort_id=2
  team: 極影
星期六,單色小姐Ⅱ:
  rss:
    KNA: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%96%AE%E8%89%B2%E5%B0%8F%7C%E7%99%BD%E5%B0%8F+team_id%3A498+%E7%B9%81+720+MP4&sort_id=2
    傲嬌零.RH: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%96%AE%E8%89%B2%E5%B0%8F%7C%E7%99%BD%E5%B0%8F+team_id%3A532+GB+720+MP4&sort_id=2
    華盟: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%96%AE%E8%89%B2%E5%B0%8F%7C%E7%99%BD%E5%B0%8F%7C%E7%99%BD%E5%A7%91+team_id%3A49+%E7%AE%80+720+MP4&sort_id=2
  team: KNA
星期六,監獄學園:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%9B%A3+%E5%9C%92+team_id%3A303+%E7%AE%80+720&sort_id=2
    幻櫻: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%9B%A3+%E5%9C%92+team_id%3A241+GB+720+MP4&sort_id=2
  team: 幻櫻
星期六,若葉女孩:
  rss:
    KNA: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%91%89%E5%A5%B3%7CWakaba+team_id%3A498+%E7%B9%81+720+MP4&sort_id=2
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%91%89%E5%A5%B3%7CWakaba+team_id%3A303+%E7%AE%80+720&sort_id=2
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%91%89%E5%A5%B3%7CWakaba+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%91%89%E5%A5%B3%7CWakaba+team_id%3A185+GB+720+MP4&sort_id=2
    澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%91%89%E5%A5%B3%7CWakaba+team_id%3A58+720+MP4&sort_id=2
  team: KNA
星期六,魔法少女☆伊莉雅2weiHerz!:
  rss:
    KNA: https://share.dmhy.org/topics/rss/rss.xml?keyword=liner%7CHerz+team_id%3A498+%E7%B9%81+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=liner%7CHerz+team_id%3A185+GB+720+MP4&sort_id=2
    澄空.華盟: https://share.dmhy.org/topics/rss/rss.xml?keyword=liner%7CHerz+team_id%3A58+720+MP4&sort_id=2
  team: 澄空.華盟
星期四,GANGSTA:
  rss:
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=GANGSTA+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    幻櫻: https://share.dmhy.org/topics/rss/rss.xml?keyword=GANGSTA+team_id%3A241+GB+720+MP4&sort_id=2
  team: 幻櫻
星期四,赤龍戰役:
  rss:
    惡魔島: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%BE%8D%E6%88%B0%E5%BD%B9+team_id%3A90+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%BE%8D%E6%88%B0%E5%BD%B9+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
星期日,Charlotte:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=Charlotte+team_id%3A303+%E7%AE%80+720&sort_id=2
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=Charlotte+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    幻之: https://share.dmhy.org/topics/rss/rss.xml?keyword=Charlotte+team_id%3A430+GB+720+MP4&sort_id=2
    惡魔島: https://share.dmhy.org/topics/rss/rss.xml?keyword=Charlotte+team_id%3A90+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=Charlotte+team_id%3A185+GB+720+MP4&sort_id=2
    澄空.雪飄: https://share.dmhy.org/topics/rss/rss.xml?keyword=Charlotte+team_id%3A58+720+MP4&sort_id=2
    輕之國度: https://share.dmhy.org/topics/rss/rss.xml?keyword=Charlotte+team_id%3A321+GB+720+MP4&sort_id=2
  team: 極影
星期日,下流梗不存在的灰暗世界:
  rss:
    輕之國度: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%B8%8B%E6%B5%81%7C%E6%9C%89%E9%BB%84+team_id%3A321+GB+720+MP4&sort_id=2
  team: 輕之國度
星期日,亞爾斯蘭戰記:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%98%AD%E6%88%B0%7CArslan+team_id%3A303+%E7%AE%80+720&sort_id=2
    惡魔島: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%98%AD%E6%88%B0%7CArslan+team_id%3A90+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%98%AD%E6%88%B0%7CArslan+team_id%3A185+GB+720+MP4&sort_id=2
    異域: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%98%AD%E6%88%B0%7CArslan+team_id%3A271+%E7%AE%80+720&sort_id=2
  team: 極影
星期日,六花的勇者:
  rss:
    幻之: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%85%AD%E8%8A%B1%E7%9A%84+team_id%3A430+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%85%AD%E8%8A%B1%E7%9A%84+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
