星期一,三顆星彩色冒險:
  rss:
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%B8%89%E9%A1%86%E6%98%9F+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
  source: share_dmhy_org
  team: 千夏
  update_interval: 7
星期二,25歲的女高中生:
  rss:
    幻櫻: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%AD%B2+%E9%AB%98%E4%B8%AD+team_id%3A241+GB+720+MP4&sort_id=2
  source: share_dmhy_org
  team: 幻櫻
  update_interval: 7
星期二,龍王的工作！:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%BE%8D%E7%8E%8B%E7%9A%84+team_id%3A303+%E7%AE%80+720&sort_id=2
  source: share_dmhy_org
  team: 動漫國
  update_interval: 7
星期五,爆肝工程師的異世界狂想曲:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%95%8C%E7%8B%82+team_id%3A185+GB+720+MP4&sort_id=2
  source: share_dmhy_org
  team: 極影
  update_interval: 7
星期五,童話魔法使:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%AB%A5%E8%A9%B1%E9%AD%94%7C%E7%AB%A5%E8%AF%9D%E4%B8%8E%7C%E5%8E%9F%E6%9B%B8+team_id%3A303+%E7%AE%80+720&sort_id=2
    届恋: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%AB%A5%E8%A9%B1%E9%AD%94%7C%E7%AB%A5%E8%AF%9D%E4%B8%8E%7C%E5%8E%9F%E6%9B%B8+team_id%3A703
    澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%AB%A5%E8%A9%B1%E9%AD%94%7C%E7%AB%A5%E8%AF%9D%E4%B8%8E%7C%E5%8E%9F%E6%9B%B8+team_id%3A58+720+MP4&sort_id=2
  source: share_dmhy_org
  team: 動漫國
  update_interval: 7
星期五,搖曳露營△:
  rss:
    DHR: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%9B%B3%E9%9C%B2+team_id%3A407
    喵萌奶茶屋.千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%9B%B3%E9%9C%B2+team_id%3A669
    紫音: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%9B%B3%E9%9C%B2+team_id%3A459
  source: share_dmhy_org
  team: 喵萌奶茶屋.千夏
  update_interval: 7
星期六,BEATLESS:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=BEATLESS+team_id%3A303+%E7%AE%80+720&sort_id=2
  source: share_dmhy_org
  team: 動漫國
  update_interval: 7
星期六,皇帝聖印戰記:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%81%96%E5%8D%B0+team_id%3A185+GB+720+MP4&sort_id=2
  source: share_dmhy_org
  team: 極影
  update_interval: 7
星期六,刀使之巫女:
  rss:
    桜都: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%88%80%E4%BD%BF+team_id%3A619
    漫貓.愛戀: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%88%80%E4%BD%BF+team_id%3A423
    茉語星夢.風之聖殿: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%88%80%E4%BD%BF+%E7%AE%80+720+team_id%3A434
  source: share_dmhy_org
  team: 茉語星夢.風之聖殿
  update_interval: 7
星期六,博多豚骨拉麵團:
  rss:
    DHR: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%8D%9A%E5%A4%9A+team_id%3A407
    幻之: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%8D%9A%E5%A4%9A+GB+720+team_id%3A430
    悠哈C9: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%8D%9A%E5%A4%9A+team_id%3A151
  source: share_dmhy_org
  team: 幻之
  update_interval: 7
星期四,紫羅蘭永恆花園:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B4%AB%E7%BE%85%E8%98%AD+team_id%3A303+%E7%AE%80+720&sort_id=2
    幻櫻: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B4%AB%E7%BE%85%E8%98%AD+team_id%3A241+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B4%AB%E7%BE%85%E8%98%AD+team_id%3A185+GB+720+MP4&sort_id=2
    澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%B4%AB%E7%BE%85%E8%98%AD+team_id%3A58+720+MP4&sort_id=2
  source: share_dmhy_org
  team: 幻櫻
  update_interval: 7
星期日,DARLING in the FRANXX:
  rss:
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=FRANXX+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
  source: share_dmhy_org
  team: 千夏
  update_interval: 7
星期日,Fate／EXTRA Last Encore:
  rss:
    喵萌茶会字幕组: https://share.dmhy.org/topics/rss/rss.xml?keyword=Fate+EXTRA+%E7%AE%80%E4%BD%93+team_id%3A468
  source: share_dmhy_org
  team: 喵萌茶会字幕组
  update_interval: 7
星期日,POP TEAM EPIC:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=POP+TEAM+EPIC+team_id%3A185+GB+720&sort_id=2
    悠哈C9字幕社: https://share.dmhy.org/topics/rss/rss.xml?keyword=POP+TEAM+EPIC+CHS&sort_id=2&team_id=151
  source: share_dmhy_org
  team: 悠哈C9字幕社
  update_interval: 7
星期日,Slow Start:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=Slow+Start+team_id%3A303+%E7%AE%80+720&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=Slow+Start+team_id%3A185+GB+720+MP4&sort_id=2
    輕之國度: https://share.dmhy.org/topics/rss/rss.xml?keyword=Slow+Start+team_id%3A321+720+MP4&sort_id=2
  source: share_dmhy_org
  team: 輕之國度
  update_interval: 7
星期日,citrus:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=citrus+team_id%3A303+%E7%AE%80+720&sort_id=2
    幻櫻: https://share.dmhy.org/topics/rss/rss.xml?keyword=citrus+team_id%3A241+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=citrus+team_id%3A185+GB+720+MP4&sort_id=2
  source: share_dmhy_org
  team: 幻櫻
  update_interval: 7
星期日,百變小櫻 透明牌篇:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%AD%94%E5%8D%A1%7C%E5%BA%AB%E6%B4%9B%7C%E7%99%BE%E8%AE%8A+team_id%3A185+GB+720+MP4&sort_id=2
    澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%AD%94%E5%8D%A1%7C%E5%BA%AB%E6%B4%9B%7C%E7%99%BE%E8%AE%8A+team_id%3A58+720+MP4&sort_id=2
  source: share_dmhy_org
  team: 澄空
  update_interval: 7
星期日,魔法使的新娘:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%AD%94%E6%B3%95%E4%BD%BF+%E6%96%B0%E5%A8%98+team_id%3A303+%E7%AE%80+720&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%AD%94%E6%B3%95%E4%BD%BF+%E6%96%B0%E5%A8%98+team_id%3A185+GB+720+MP4&sort_id=2
  source: share_dmhy_org
  team: 動漫國
  update_interval: 7
