username: 'username@163.com'
password: 'password'
dldir: '/home'
HttpProxy: '192.168.1.1:8080'
toMail: 'toMail@qq.com'
transmissionrpc_server: '127.0.0.1'
transmissionrpc_user: 'your_username'
transmissionrpc_password: 'your_password'
transmissionrpc_download_path: '/home'
