星期一,小魔女學園:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%B0%8F%E9%AD%94%E5%A5%B3%E5%AD%B8+team_id%3A303+%E7%AE%80+720&sort_id=2
    千夏.茉語: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%B0%8F%E9%AD%94%E5%A5%B3%E5%AD%B8+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%B0%8F%E9%AD%94%E5%A5%B3%E5%AD%B8+team_id%3A185+GB+720+MP4&sort_id=2
  team: 千夏.茉語
  update_interval: 7
星期三,末日時在做什麼？有沒有空？可以來拯救嗎？:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%9C%AB%E6%97%A5%E6%99%82+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
  update_interval: 7
星期二,不正經的魔術講師與禁忌教典:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%B8%8D%E6%AD%A3%E7%B6%93+team_id%3A303+%E7%AE%80+720&sort_id=2
    幻之: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%B8%8D%E6%AD%A3%E7%B6%93+team_id%3A430+GB+720&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%B8%8D%E6%AD%A3%E7%B6%93+team_id%3A185+GB+720+MP4&sort_id=2
    輕之國度: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E4%B8%8D%E6%AD%A3%E7%B6%93+team_id%3A321+GB+MP4&sort_id=2
  team: 輕之國度
  update_interval: 7
星期二,從零開始的魔法書:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%BE%9E%E9%9B%B6%E9%96%8B%E5%A7%8B%E7%9A%84%E9%AD%94%E6%B3%95%E6%9B%B8+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
  update_interval: 7
星期五,不起眼女主角培育法♭:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%9C%BC%E5%A5%B3%E4%B8%BB%7C%E4%BA%BA%E5%A5%B3%E4%B8%BB+team_id%3A303+%E7%AE%80+720&sort_id=2
    幻櫻: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%9C%BC%E5%A5%B3%E4%B8%BB%7C%E4%BA%BA%E5%A5%B3%E4%B8%BB+team_id%3A241+GB+720+MP4&sort_id=2
    輕之國度: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E7%9C%BC%E5%A5%B3%E4%B8%BB%7C%E4%BA%BA%E5%A5%B3%E4%B8%BB+team_id%3A321+GB+720+MP4&sort_id=2
  team: 幻櫻
  update_interval: 7
星期五,戀愛暴君:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%84%9B%E6%9A%B4+team_id%3A303+%E7%AE%80+720&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%84%9B%E6%9A%B4+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
  update_interval: 7
星期五,時鐘機關之星:
  rss:
    澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%A9%9F%E9%97%9C%E4%B9%8B%E6%98%9F+team_id%3A58+720+MP4&sort_id=2
  team: 澄空
  update_interval: 7
星期五,雛子的筆記:
  rss:
    幻之: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%9B%9B%E5%AD%90+team_id%3A430+GB+720+MP4&sort_id=2
    澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%9B%9B%E5%AD%90+team_id%3A58+720+MP4&sort_id=2
  team: 幻之
  update_interval: 7
星期六,巴哈姆特之怒VIRGIN SOUL:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%B7%B4%E5%93%88%E5%A7%86%E7%89%B9+Virgin+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
  update_interval: 7
星期六,正確的卡多:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%A7%A3%E5%8D%A1%7C%E7%9A%84%E5%8D%A1%E5%A4%9A%7C%E7%9A%84Kado+team_id%3A303+%E7%AE%80+720&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%A7%A3%E5%8D%A1%7C%E7%9A%84%E5%8D%A1%E5%A4%9A%7C%E7%9A%84Kado+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
  update_interval: 7
星期六,Re：CREATORS:
  rss:
    DHR: https://share.dmhy.org/topics/rss/rss.xml?keyword=Re+Creators+team_id%3A407
    桜都: https://share.dmhy.org/topics/rss/rss.xml?keyword=Re+Creators+team_id%3A619
    豌豆.&風之聖殿: https://share.dmhy.org/topics/rss/rss.xml?keyword=Re+Creators+team_id%3A434+%E7%AE%80
    追放: https://share.dmhy.org/topics/rss/rss.xml?keyword=Re+Creators+team_id%3A616
  source: share_dmhy_org
  team: 豌豆.&風之聖殿
  update_interval: 7
星期四,SAKURA QUEST:
  rss:
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=sakura+quest+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    幻櫻: https://share.dmhy.org/topics/rss/rss.xml?keyword=sakura+quest+team_id%3A241+GB+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=sakura+quest+team_id%3A185+GB+720&sort_id=2
  team: 千夏
  update_interval: 7
星期四,武裝少女Machiavellianism:
  rss:
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%AD%A6%E8%A3%9D+Machi+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
  update_interval: 7
星期四,重啟咲良田:
  rss:
    千夏: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%92%B2%E8%89%AF%E7%94%B0+team_id%3A283+%E7%B9%81+720+MP4&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E5%92%B2%E8%89%AF%E7%94%B0+team_id%3A185+GB+720+MP4&sort_id=2
  team: 極影
  update_interval: 7
星期日,情色漫畫老師:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%83%85%E8%89%B2%E6%BC%AB%7C%E9%BB%84%E6%BC%AB+team_id%3A303+%E7%AE%80+720&sort_id=2
    澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E6%83%85%E8%89%B2%E6%BC%AB%7C%E9%BB%84%E6%BC%AB+team_id%3A58+720+MP4&sort_id=2
  team: 澄空
  update_interval: 7
星期日,愛麗絲與藏六:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%88%87%E8%97%8F%E5%85%AD+team_id%3A303+%E7%AE%80+720&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%88%87%E8%97%8F%E5%85%AD+team_id%3A185+GB+720+MP4&sort_id=2
  team: 動漫國
  update_interval: 7
星期日,碧藍幻想:
  rss:
    天香.A.I.R.nes: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%97%8D%E5%B9%BB+team_id%3A222
    雪飄.澄空: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%97%8D%E5%B9%BB+team_id%3A37+%E7%AE%80+720
  team: 雪飄.澄空
  update_interval: 7
星期日,進擊的巨人Ⅱ:
  rss:
    動漫國: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%80%B2%E6%93%8A+team_id%3A303+%E7%AE%80+720&sort_id=2
    極影: https://share.dmhy.org/topics/rss/rss.xml?keyword=%E9%80%B2%E6%93%8A+team_id%3A185+GB+720+MP4&sort_id=2
  team: 動漫國
  update_interval: 7
